name: p_pay
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter_stripe: ^10.0.0
  # Slide Panal
  sliding_up_panel: ^2.0.0+1
  # QR Code
  qr_flutter: ^4.1.0
  #image picker
  image_picker: ^1.0.7
  #get Storage
  get_storage: ^2.1.1
  #Credit Card
  flutter_credit_card: ^4.0.1
  #Chart
  syncfusion_flutter_charts: ^23.1.38
  #International phone number
  intl_phone_field: ^3.2.0
  #Svg
  flutter_svg: ^2.0.8
  cupertino_icons: ^1.0.2
  #State Management
  get: 4.6.6
  #Google Font
  google_fonts: 6.1.0
  #QR Code Scanner
  qr_code_scanner: ^1.0.1
  #Carousel Slider
  carousel_slider: ^4.2.1
  #Dot Indicator
  dots_indicator: ^3.0.0
  #Percent Indicator
  percent_indicator: ^4.2.3
  #http:
  http: ^1.1.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/loder/

